language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy/ && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/blitz.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: blita-springboot-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deploy: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: blitz-group
      key: blitz.zip
      bundle_type: zip
      application: blitz
      deployment_group: blitz-group
      region : ap-northeast-2
      wait-until-deployed:  true



# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - denhenker@naver.com