spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blitz
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
     # show_sql: true
      format_sql: true
  profiles:
    include: oauth
  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace